[package]
name = "project-parser"
version = "0.1.0"
authors = ["Fulvio Gentile <fulvio.gentile@into.care>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
serde_json = "1.0"